### ISSUE TITLE
App crashes on GenyMotion

### ISSUE THREAD

**Issue by genidma** [romainguy/google-io-2014#10]
Hi, 
- The app compiles properly on Geny motion. But when I click on an image, it crashes.
  "Unfortunately, Google I/O 2014 has stopped". 
- App works just fine on the native emulator. 

Thanks

**Comment by lambor** [comment]
it seems OOM happened. i just add  

> android:largeHeap="true"

  in application tag content

**Comment by lambor** [comment]
i found it also not help...
