### ISSUE TITLE
Map Fragment @ activity_detail.xml

### ISSUE THREAD

**Issue by zcelaloglu** [romainguy/google-io-2014#7]
map:uiRotateGestures="false"
                    map:uiScrollGestures="false"
                    map:uiTiltGestures="false"
                    map:uiZoomControls="false"
                    map:uiZoomGestures="false"

these lines gives an error so App crashes at first time launching

Btw,I generated API KEY from Google APIs Console

What's the solution of this ?

**Comment by romainguy** [comment]
Android Studio highlights these lines as errors but it looks like a bug in Studio itself. These lines would produce a compilation error if they were wrong, not a runtime crash. What is the stack trace of the crash you are experiencing?

**Comment by Chris-Aranha** [comment]
I'm getting the same crash when using Android Studio... more specifically the app launches but as soon as you press any buttons it crashes. 

![screen shot 2015-02-12 at 23 36 57](https://cloud.githubusercontent.com/assets/845919/6179316/127268c8-b310-11e4-95d1-49a0a8488fcd.png)

**Comment by romainguy** [comment]
The crash is pretty self explanatory. You do not have Google Play Services on your device. Note that you also need to generate a Google Maps v2 API key.

**Comment by Chris-Aranha** [comment]
Thanks @romainguy ... works perfectly now.  :-)
