### ISSUE TITLE
Sample is very slow on Nexus 4 + can't import using Android-studio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [romainguy/google-io-2014#9]
The Nexus 4 is quite slow using this sample app. This includes the scrolling and the special transition effect.
Even if I remove all of the effects , the tinting and the animations, remove all ImageViews except for one, and use a single effect of transition, I get a tiny delay between the time I click the ImageView and the time it actually starts the transition.

Also, for some reason Android-Studio failed to import it, so I used Eclipse.
This is what I see :
![untitled20141123152918](https://cloud.githubusercontent.com/assets/5357526/5157704/947b4cde-7325-11e4-9f84-8d9f94ac5ade.png)

As you can see, I get this error even though I have the canary build...

Can anyone please help?

**Comment by romainguy** [comment]
This project is setup for beta builds, not canary builds.

## 

Romain Guy
http://www.curious-creature.org
http://google.com/+RomainGuy

**Comment by AndroidDeveloperLB** [comment]
Odd. I thought it should work for it too, especially now that it's on RC ...

Anyway, why is the sample so slow in it original form? 
Also, can you please publish a minimized sample of it (one that only has the tranistion)  ? Would it be possible to add this functionality to the support library too? 

I also wonder how it will perform in case the activities work in different orientation (which can occur, for example, if the app wishes to show landscape photos in landscape mode).

**Comment by romainguy** [comment]
This sample is already pretty minimal, it doesn't need to be any smaller.

**Comment by AndroidDeveloperLB** [comment]
I know it's nice to show a lot of cool effects, but when you want to learn how to perform the transition, you get a lot of other things to notice in this sample. 
This is not a good practice to teach others of how to use this new API. A better thing would be to show a "simple" example and an "advanced" example.
Just like for a "Hello world", you can use OpenGL to show it, with fire and smoke and a lot of special effects, or you can use a TextView .
Using a TextView would show the basic way to show the text, while the other solution would only confuse people who are unfamiliar to OpenGL . 
In addition, just like here, the sample of OpenGL is much slower than the basic example, at least according to what I've tested (Nexus 4, with Lollipop) .
In the current sample, I can't find out the minimal code and style that is needed, so I have to remove and remove and see what happens.
Speaking of OpenGL, why does the project require OpenGL 2 ?

**Comment by romainguy** [comment]
There is some confusion here: this app was written for a Google I/O talk where everything is clearly explained. The goal of this sample is not to replace the platform's API Demos, which are available from the SDK manager and provide much more targeted samples.

OpenGL ES 2.0 is required because of the MapView used in the details activity. It's not a problem though since any device running Android 5.0 supports OpenGL ES 2.0.

**Comment by AndroidDeveloperLB** [comment]
1.Why did you close the issue? I asked why it's slow on the Nexus 4, and I still don't know the main reason...

2.The API demos are named "legacy" for some reason, and cannot be easily imported as in the previous versions, not even on Eclipse.
Maybe you are talking about this website:
http://developer.android.com/samples/ActivitySceneTransitionBasic/index.html
?
If so, its documentation of how to import it isn't updated:
http://developer.android.com/samples/index.html
It says to use "file"->" Import Project " , but when you open Android-Studio, there is no "file" menu. 
I've only succeeded importing this project via Eclipse, and just like this sample here, it's way more complicated than what it can be. It even has more files. Even after running this sample app (without compilation issues), it crashes :

11-23 18:07:20.950: E/AndroidRuntime(2141): Process: com.example.android.activityscenetransitionbasic, PID: 2141
11-23 18:07:20.950: E/AndroidRuntime(2141): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.activityscenetransitionbasic/com.example.android.activityscenetransitionbasic.MainActivity}: java.lang.RuntimeException: Unknown scene name: moveImage
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.app.ActivityThread.access$800(ActivityThread.java:144)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.os.Handler.dispatchMessage(Handler.java:102)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.os.Looper.loop(Looper.java:135)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.app.ActivityThread.main(ActivityThread.java:5221)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at java.lang.reflect.Method.invoke(Native Method)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at java.lang.reflect.Method.invoke(Method.java:372)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
11-23 18:07:20.950: E/AndroidRuntime(2141): Caused by: java.lang.RuntimeException: Unknown scene name: moveImage
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.transition.TransitionInflater.createTransitionFromXml(TransitionInflater.java:177)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.transition.TransitionInflater.createTransitionFromXml(TransitionInflater.java:181)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.transition.TransitionInflater.inflateTransition(TransitionInflater.java:77)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at com.android.internal.policy.impl.PhoneWindow.getTransition(PhoneWindow.java:3696)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3657)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:367)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.app.Activity.setContentView(Activity.java:2144)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at com.example.android.activityscenetransitionbasic.MainActivity.onCreate(MainActivity.java:47)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.app.Activity.performCreate(Activity.java:5933)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
11-23 18:07:20.950: E/AndroidRuntime(2141):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)

3.Can you please update the sample app project, so that it would be possible to import it on Android-Studio ?

4.If the sample is for Android 5.0 and above, and you say that any device that has it must support OpenGL ES 2.0 ,  why state that it requires OpenGL ES 2.0 ? Would custom ROMs on old devices still be able to launch it?

5.Speaking of the lecture, I want to say you guys are awesome in lectures.
